name: calcom-pycalcx
version: '1.0'
#version-script: git describe --abbrev=1 --tags
summary: python test package
description: |
 Calcom by PyCalc X
base: core18
grade: stable
confinement: strict

apps:
  testapp:
    command: bin/calcom-pycalcx
    plugs: [home,network-bind]
parts:
  calcom-pycalcx:
    plugin: python
    python-version: python3
    source: 
    stage-packages: [ncbi-blast+]